//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moorbot.Main.Storage {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Photos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Photos() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moorbot.Main.Storage.Photos", typeof(Photos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__1 {
            get {
                object obj = ResourceManager.GetObject("_result__1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__10 {
            get {
                object obj = ResourceManager.GetObject("_result__10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__11 {
            get {
                object obj = ResourceManager.GetObject("_result__11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__12 {
            get {
                object obj = ResourceManager.GetObject("_result__12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__13 {
            get {
                object obj = ResourceManager.GetObject("_result__13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__14 {
            get {
                object obj = ResourceManager.GetObject("_result__14", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__15 {
            get {
                object obj = ResourceManager.GetObject("_result__15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__16 {
            get {
                object obj = ResourceManager.GetObject("_result__16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__17 {
            get {
                object obj = ResourceManager.GetObject("_result__17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__18 {
            get {
                object obj = ResourceManager.GetObject("_result__18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__19 {
            get {
                object obj = ResourceManager.GetObject("_result__19", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__2 {
            get {
                object obj = ResourceManager.GetObject("_result__2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__20 {
            get {
                object obj = ResourceManager.GetObject("_result__20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__21 {
            get {
                object obj = ResourceManager.GetObject("_result__21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__22 {
            get {
                object obj = ResourceManager.GetObject("_result__22", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__23 {
            get {
                object obj = ResourceManager.GetObject("_result__23", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__24 {
            get {
                object obj = ResourceManager.GetObject("_result__24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__25 {
            get {
                object obj = ResourceManager.GetObject("_result__25", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__26 {
            get {
                object obj = ResourceManager.GetObject("_result__26", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__27 {
            get {
                object obj = ResourceManager.GetObject("_result__27", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__28 {
            get {
                object obj = ResourceManager.GetObject("_result__28", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__29 {
            get {
                object obj = ResourceManager.GetObject("_result__29", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__3 {
            get {
                object obj = ResourceManager.GetObject("_result__3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__30 {
            get {
                object obj = ResourceManager.GetObject("_result__30", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__31 {
            get {
                object obj = ResourceManager.GetObject("_result__31", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__32 {
            get {
                object obj = ResourceManager.GetObject("_result__32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__33 {
            get {
                object obj = ResourceManager.GetObject("_result__33", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__34 {
            get {
                object obj = ResourceManager.GetObject("_result__34", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__35 {
            get {
                object obj = ResourceManager.GetObject("_result__35", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__36 {
            get {
                object obj = ResourceManager.GetObject("_result__36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__37 {
            get {
                object obj = ResourceManager.GetObject("_result__37", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__38 {
            get {
                object obj = ResourceManager.GetObject("_result__38", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__39 {
            get {
                object obj = ResourceManager.GetObject("_result__39", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__4 {
            get {
                object obj = ResourceManager.GetObject("_result__4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__40 {
            get {
                object obj = ResourceManager.GetObject("_result__40", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__41 {
            get {
                object obj = ResourceManager.GetObject("_result__41", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__42 {
            get {
                object obj = ResourceManager.GetObject("_result__42", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__5 {
            get {
                object obj = ResourceManager.GetObject("_result__5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__6 {
            get {
                object obj = ResourceManager.GetObject("_result__6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__7 {
            get {
                object obj = ResourceManager.GetObject("_result__7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__8 {
            get {
                object obj = ResourceManager.GetObject("_result__8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result__9 {
            get {
                object obj = ResourceManager.GetObject("_result__9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа byte[].
        /// </summary>
        internal static byte[] _result_0 {
            get {
                object obj = ResourceManager.GetObject("_result_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
